CREATE TABLE DEPARTMENTS (
	DEPTNO NUMBER NOT NULL,
	DEPTNAME VARCHAR2(20) NOT NULL,
	LOCATION VARCHAR2(20)
);

COMMENT ON TABLE DEPARTMENTS IS '부서테이블';

COMMENT ON COLUMN DEPARTMENTS.DEPTNO IS '부서번호';

COMMENT ON COLUMN DEPARTMENTS.DEPTNAME IS '부서이름';

COMMENT ON COLUMN DEPARTMENTS.LOCATION IS '부서위치';

CREATE UNIQUE INDEX PK_DEPARTMENTS
	ON DEPARTMENTS (
		DEPTNO ASC
	);

ALTER TABLE DEPARTMENTS
	ADD
		CONSTRAINT PK_DEPARTMENTS
		PRIMARY KEY (
			DEPTNO
		);

CREATE TABLE EMPLOYEES (
	EMPNO NUMBER NOT NULL,
	EMPNAME VARCHAR2(20) NOT NULL,
	SSN VARCHAR2(13) NOT NULL,
	MOBILE VARCHAR2(20),
	REG_DATE DATE DEFAULT sysdate,
	DEPTNO NUMBER
);

COMMENT ON TABLE EMPLOYEES IS '사원테이블';

COMMENT ON COLUMN EMPLOYEES.EMPNO IS '사원번호';

COMMENT ON COLUMN EMPLOYEES.EMPNAME IS '사원이름';

COMMENT ON COLUMN EMPLOYEES.SSN IS '주민번호';

COMMENT ON COLUMN EMPLOYEES.MOBILE IS '전화번호';

COMMENT ON COLUMN EMPLOYEES.REG_DATE IS '입사일자';

COMMENT ON COLUMN EMPLOYEES.DEPTNO IS '부서번호';

CREATE UNIQUE INDEX PK_EMPLOYEES
	ON EMPLOYEES (
		EMPNO ASC
	);

ALTER TABLE EMPLOYEES
	ADD
		CONSTRAINT PK_EMPLOYEES
		PRIMARY KEY (
			EMPNO
		);

CREATE TABLE SALARY (
	EMPNO NUMBER NOT NULL,
	CLASS CHAR(1) NOT NULL,
	SALARY NUMBER(10) DEFAULT 0 NOT NULL
);

COMMENT ON TABLE SALARY IS '급여테이블';

COMMENT ON COLUMN SALARY.EMPNO IS '사원번호';

COMMENT ON COLUMN SALARY.CLASS IS '급여구분';

COMMENT ON COLUMN SALARY.SALARY IS '급여';

CREATE UNIQUE INDEX PK_SALARY
	ON SALARY (
		EMPNO ASC
	);

ALTER TABLE SALARY
	ADD
		CONSTRAINT PK_SALARY
		PRIMARY KEY (
			EMPNO
		);

ALTER TABLE EMPLOYEES
	ADD
		CONSTRAINT FK_DEPARTMENTS_TO_EMPLOYEES
		FOREIGN KEY (
			DEPTNO
		)
		REFERENCES DEPARTMENTS (
			DEPTNO
		);

ALTER TABLE SALARY
	ADD
		CONSTRAINT FK_EMPLOYEES_TO_SALARY
		FOREIGN KEY (
			EMPNO
		)
		REFERENCES EMPLOYEES (
			EMPNO
		);